# Generated by Django 4.2.7 on 2023-11-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите название фильма')),
                ('country', models.CharField(max_length=100, verbose_name='Укажите название страны')),
                ('image', models.ImageField(upload_to='films/')),
                ('genre', models.CharField(choices=[('Horror', 'Horror'), ('Dramma', 'Dramma')], max_length=100)),
                ('director', models.CharField(max_length=100, verbose_name='Укажите директора')),
                ('description', models.TextField(blank=True, verbose_name='Укажите описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
