# Generated by Django 4.2.7 on 2023-11-28 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_reviewfilmmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewfilmmodel',
            name='film_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_object', to='main_page.filmmodel'),
        ),
    ]
